baseURL = "/"
languageCode = "en-us"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Assessment Form"
url = "/assessment-form"
weight = 4
[[menu.main]]
name = "Professional Summary"
url = "/about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
